name: C/C++ CI

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - master         # Push events on master branch
    # Sequence of patterns matched against refs/tags
    tags:        
      - v*

env:
  VERSION: 0.73

jobs:
  build:
    name: Windows 32bits
    runs-on: ubuntu-latest
    
    steps:
    
    # Checkout
    - uses: actions/checkout@v2
    
    # Build
    - name: build
      run: |
        mkdir ../builds
        docker run --rm -i -v $(pwd)/../builds:/builds -v $(pwd):/sources cyd01/cross-gcc "cd ${VERSION}_My_PuTTY/windows ; make -f MAKEFILE.MINGW cross ; cd /builds ; ls -l"
        mv -f $(pwd)/../builds ./
        cd builds ; zip kitty.zip *.exe

    # Upload runner package tar.gz/zip as artifact
    - name: Publish Artifact
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@v1
      with:
        name: kitty-${VERSION}.zip
        path: builds/kitty.zip
